version: "3.3"
services:
  postgres:
    image: postgres:14.9
    container_name: ${POSTGRES_HOST}
    restart: always
    volumes:
      - ${PGDATA}:${PGDATA}
    ports:
      - 5432:5432
    env_file:
      - .env


  frontend:
    build:
      dockerfile: frontend/Dockerfile.frontend
      context: .
    container_name: frontend
    restart: always
    ports:
      - 4200:4200
    volumes:
      - .:/frontend
      - /frontend/node_modules
    command: >
      bash -c "cd /pets-service/frontend && ng serve --disable-host-check"


  backend:
    build:
      dockerfile: Dockerfile.backend
      context: .
    container_name: backend
    restart: always
    volumes:
      - /opt/pets-service/staticfiles/:/pets-service/staticfiles/
      - /opt/pets-service/media/:/pets-service/media/
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      frontend:
        condition: service_started
      postgres:
        condition: service_started
    command: >
      bash -c "gunicorn -w 5 -b 0.0.0.0:8080 pets_viewer.wsgi:application"