# Generated by Django 3.2.15 on 2023-12-04 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Вид')),
                ('name', models.CharField(max_length=30, verbose_name='Кличка')),
                ('breed', models.CharField(max_length=30, verbose_name='Порода')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Домашнее животное',
                'verbose_name_plural': 'Домашние животные',
            },
        ),
    ]
